feat: add strel_split
JuliaImages/ImageMorphology.jl pull request #95
Opened 2022-06-03 20:01 UTC by johnnychen94

Handling SE usually contributes a small portion of time (<0.5%) to the real morphological computation.
For this reason, I believe there's no need to worry about the "what if I only need to use the upper half" issue.

I could be wrong, however. @ThomasRetornaz what's your thought?

Tests are needed.

2022-06-06 08:39 UTC, ThomasRetornaz commented on src/StructuringElements/utils.jl
> +```
Warning if it remind it properly Erode(Erode(Lower),upper)!=Erode(diamond) the composition lower+upper is not equivalent
Todo check this with tests :)

2022-06-06 08:42 UTC, ThomasRetornaz requested changes
I m just worried on SE composition, i m not sure  aply erode(upper+lower)==Erode(upper(erode(lower))
We will ensure that with tests :)

2022-06-08 02:54 UTC, ThomasRetornaz commented
My bad i misunderstood the applications
Its not se decomposition. its helpers for other algorithms 🙂
So of course the pr is ok

2022-06-13 04:05 UTC, johnnychen94 reviewed
Yeap, this is a part of the work to cleanup and upgrade `label_components` function. It's also used in #60 so I figure it's convenient to make it an internal function. I've updated the docs to avoid confusion on the non-yet-existed `strel_decompose`.

2022-06-13 04:11 UTC, merged